@startuml datamodel

!define table(name,desc) class name as "desc"
!define primary_key(x) <b>x</b>
!define foreign_key(x) #x

table(Client, "Client") {
  primary_key(id): int
  name: string
  email: string
  +create(name: string, email: string): void
  +update(id: int, name: string, email: string): void
  +delete(id: int): void
}

table(Phone, "Phone") {
  primary_key(id): int
  name: string
  model: string
  brand: string
  quantity: int
  +create(name: string, model: string, brand: string, quantity: int): void
  +update(id: int, name: string, model: string, brand: string, quantity: int): void
  +delete(id: int): void
}

table(User, "User") {
  username: string
  email: string
  password: string
  foreign_key(client_id): Client
  +create(username: string, email: string, password: string, client: Client): void
  +update(id: int, username: string, email: string, password: string, client: Client): void
  +delete(id: int): void
}



Client "1" -- "many" User : client_id



@enduml
